### ISSUE TITLE
rerun please

### ISSUE THREAD

**Issue by markcollier** [matteodefelice/c3s-xskillscore#1]
Hi I was able to work my way through your example, it is nice to be able to effectively generate results effectively on the cloud. I noticed that the calls to crps_ensemble and crps_ensemble need dim='time' to return x,y result presumably the api has changed since the notebook was written. However, I am able to reproduce the correlation plot, but the second and (especially) the third plot look quite different, and I am not sure why that would be as if the correlation plot is the same then how could the others have changed so substantially? Unless the calculation or a bug was fixed in xskillscore? I can provide further details or perhaps you can rerun the script to see if the result now changes. I can provide my versions of the plots if required. Cheers, M.

**Comment by matteodefelice** [comment]
Yes, something has happened because with the latest environment the code doesn't run any more, I get an Illegal Instruction 4 during the regridding. I am investigating...

**Comment by matteodefelice** [comment]
Ok now you can run the notebook, it works, I have changed the call to the skillscore functions.
